
const ADDRESS_JSON_PATH = "build/addresses.json";

const MIN_DEPOSIT_SIZE = 1e18;
const EPOCH_LENGTH = 20;

const DYNASTY_LOGOUT_DELAY = 0;
const WITHDRAWAL_DELAY = 0;

const MIN_BUY_ORDER_AMOUNT = 0.01e18;
const MIN_SELL_ORDER_AMOUNT = 0.01e18;

const GOV_TOKEN_INITIAL_SUPPLY = 1000e18;

const DEBATING_PERIOD_BLOCKS = 20;
const QUORUM_FRACTION_MULTIPLIED = 0.5e18;

module.exports = {
    ADDRESS_JSON_PATH: ADDRESS_JSON_PATH,

    MIN_DEPOSIT_SIZE: MIN_DEPOSIT_SIZE,
    EPOCH_LENGTH: EPOCH_LENGTH,
    DYNASTY_LOGOUT_DELAY: DYNASTY_LOGOUT_DELAY,
    WITHDRAWAL_DELAY: WITHDRAWAL_DELAY,

    MIN_BUY_ORDER_AMOUNT: MIN_BUY_ORDER_AMOUNT,
    MIN_SELL_ORDER_AMOUNT: MIN_SELL_ORDER_AMOUNT,

    GOV_TOKEN_INITIAL_SUPPLY: GOV_TOKEN_INITIAL_SUPPLY,

    DEBATING_PERIOD_BLOCKS: DEBATING_PERIOD_BLOCKS,
    QUORUM_FRACTION_MULTIPLIED: QUORUM_FRACTION_MULTIPLIED
};